# Copyright 2020-present Sonatype Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: 2.1

orbs:
    node: circleci/node@5.1.0

jobs:
    build_and_test:
        docker:
            - image: 'cimg/base:stable'
        resource_class: medium+
        steps:
            - checkout
            - node/install:
                  install-yarn: true
                  node-version: '18.14.2' # LTS of 18 @ 24-Feb-2023
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  name: Confirm Node Version
                  command: node --version
            - run:
                  name: Inject GA Configuration
                  command: |
                      sed -i -r "s/GA_MEASUREMENT_ID/$GA_MEASUREMENT_ID/g" src/utils/AnalyticsConfg.ts && 
                      sed -i -r "s/GA_API_SECRET/$GA_API_SECRET/g" src/utils/AnalyticsConfg.ts
            - run:
                  name: Lint
                  command: yarn run lint
            - run:
                  name: Build
                  command: yarn webpack --mode production --env production --no-watch
            - run:
                  name: Test
                  command: yarn run test
            - run:
                  name: Create ZIP of Build
                  command: cd build && zip -r sonatype-platform-browser-extension.zip * && cd ..
            - store_artifacts:
                  path: build/sonatype-platform-browser-extension.zip
                  destination: sonatype-platform-browser-extension.zip

      page_parsing_test:
        docker:
            - image: 'cimg/base:stable'
        resource_class: medium+
        steps:
            - checkout
            - node/install:
                  install-yarn: true
                  node-version: '18.14.2' # LTS of 18 @ 24-Feb-2023
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  name: Confirm Node Version
                  command: node --version
            - run:
                  name: Lint
                  command: yarn run lint
            - run:
                  name: Build
                  command: yarn webpack --mode production --env production --no-watch
            - run:
                  name: Update test data
                  command: update-test-data.sh
                  working_directory: src/utils/PageParsing/testdata
            - run:
                  name: Test
                  command: yarn run test

      release_build:
        docker:
            - image: 'cimg/base:stable'
        resource_class: medium+
        steps:
            - checkout
            - node/install:
                  install-yarn: true
                  node-version: '18.14.2' # LTS of 18 @ 24-Feb-2023
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  name: Confirm Node Version
                  command: node --version
            - run:
                  name: Inject Production GA Configuration
                  command: |
                      sed -i -r 's|/debug/|/|g' src/utils/AnalyticsConfg.ts && 
                      sed -i -r "s/GA_MEASUREMENT_ID/$GA_MEASUREMENT_ID/g" src/utils/AnalyticsConfg.ts && 
                      sed -i -r "s/GA_API_SECRET/$GA_API_SECRET/g" src/utils/AnalyticsConfg.ts
            - run:
                  name: Lint
                  command: yarn run lint
            - run:
                  name: Build
                  command: yarn webpack --mode production --env production --no-watch
            - run:
                  name: Test
                  command: yarn run test
            - run:
                  name: Semantic Release
                  command: npx semantic-release

workflows:
    ci:
        jobs:
            - build_and_test:
                context:
                    - sonatype-browser-extension-build
                filters:
                    branches:
                        ignore: main

    page_parsing:
        triggers:
            schedule:
                cron: "0 5 * * 0"
                filters:
                    branches:
                        only:
                            - main
        jobs:
            - page_parsing_test

    release:
        jobs:
            - release_build:
                context:
                    - sonatype-browser-extension
                    - sonatype-browser-extension-build
                filters:
                    branches:
                        only: main
