/*
 * Copyright (c) 2019-present Sonatype, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Base Error type for any Error generated by our Extension code.
 */
export class ExtensionError extends Error {}

/**
 * Base class for general connectivity errors with Sonatype IQ Server.
 * 
 * These may be specialised in later releases.
 */
export class GeneralConnectivityError extends ExtensionError {}

/**
 * Error thrown when configuration of the extension is invalid.
 *
 * For example - attempting to access IQ configuration when data source is set to OSS INDEX.
 */
export class InvalidConfigurationError extends ExtensionError {}

/**
 * Error thrown when configuration of the extension is incomplete.
 *
 * For example - attempting to access IQ configuration when data source is set to OSS INDEX.
 */
export class IncompleteConfigurationError extends ExtensionError {}

/**
 * Sometimes Sonatype IQ experiences and error - this is used to wrap that.
 * 
 * Examples: IQ cannot connect to HDS
 */
export class SonatypeIqError extends ExtensionError { }

/**
 * Error thrown when the configured credentials are invalid.
 *
 */
export class UserAuthenticationError extends ExtensionError { }

/**
 * We parsed a page of a supported Registry, but found no Components
 */
export class NoComponentsForEvaluationError extends ExtensionError { }