name: Continuous Integration

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
    pull_request:
        paths-ignore:
            - 'README.md'
    push:
        branches:
            - main

env:
    LC_APPLICATION_ID: sonatype-platform-browser-extension

# Testing only needs permissions to read the repository contents.
permissions:
    contents: read

jobs:
    build:
        name: Build & Test
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            - name: NPM install
              run: npm i

            - name: Build
              run: npm run prod

            - name: Run Tests
              run: npm run test

    sonatype:
        name: Sonatype Lifecycle
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            # See https://help.sonatype.com/en/npm-application-analysis.html
            - name: Install Production Node Dependencies
              run: npm install --production

            - name: Sonatype Lifecycle Evaluation
              id: evaluate
              uses: sonatype/actions/evaluate@v1
              with:
                  iq-server-url: ${{ vars.SONATYPE_PLATFORM_URL }}
                  username: ${{ secrets.SONATYPE_LIFECYCLE_USERNAME }}
                  password: ${{ secrets.SONATYPE_LIFECYCLE_PASSWORD }}
                  application-id: ${{ env.LC_APPLICATION_ID }}
                  scan-targets: 'package-lock.json package.json src'
