name: Release

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    LC_APPLICATION_ID: sonatype-platform-browser-extension

permissions:
    contents: write

jobs:
    sonatype:
        name: Sonatype Lifecycle
        runs-on: ubuntu-latest
        timeout-minutes: 5
      
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            # See https://help.sonatype.com/en/npm-application-analysis.html
            - name: Install Production Node Dependencies
              run: npm install --production

            - name: Sonatype Lifecycle Evaluation
              id: evaluate
              uses: sonatype/actions/evaluate@v1
              with:
                  iq-server-url: ${{ vars.SONATYPE_PLATFORM_URL }}
                  username: ${{ secrets.SONATYPE_LIFECYCLE_USERNAME }}
                  password: ${{ secrets.SONATYPE_LIFECYCLE_PASSWORD }}
                  application-id: ${{ env.LC_APPLICATION_ID }}
                  scan-targets: 'package-lock.json package.json src'
                  stage: release

    release:
        name: Build, Release and Publish
        runs-on: ubuntu-latest
        needs:
          - sonatype
        timeout-minutes: 15
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
              with:
                persist-credentials: false

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'

            - name: NPM install
              run: npm i
              
            - name: Inject Git Commit Hash
              run: |
                sed -i -r 's|UNSTABLE|${{ github.ref }}|g' src/common/constants.ts

            - name: Inject Production Google Analytics Configuration
              run: |
                  sed -i -r 's|/debug/|/|g' src/utils/AnalyticsConfg.ts && 
                  sed -i -r "s/GA_MEASUREMENT_ID/$GA_MEASUREMENT_ID/g" src/utils/AnalyticsConfg.ts && 
                  sed -i -r "s/GA_API_SECRET/$GA_API_SECRET/g" src/utils/AnalyticsConfg.ts
              env:
                GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
                GA_API_SECRET: ${{ secrets.GA_API_SECRET }}

            - name: Build
              run: npm run prod

            - name: Semantic Release
              run: npx semantic-release
              env:
                EDGE_ACCESS_TOKEN_URL: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
                EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
                EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
                EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
                EDGE_SUBMISSION_NOTES: ${{ secrets.EDGE_SUBMISSION_NOTES }}
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}

    